server/core/urls.py
from django.urls import path, include, re_path
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'api/jobs', views.JobViewSet)

urlpatterns = [
    path('', views.index),
    path('index', views.index, name='index'),
    path('login', views.login_page, name='login'),
    path('queue', views.queue_page, name='queue'),
    path('results', views.results_page, name='results'),
    path('publications', views.publications_page, name='publications'),
    path('contact', views.contact_page, name='contact'),
    path('signup', views.signup_page, name='signup'),
    path('logout', views.logout_page, name='logout'),
    path('details', views.details_page, name='details'),
    path('download_file', views.download_file, name='download_file'),
    path('restart_job', views.restart_job, name='restart_job'),
    path('cancel_job', views.cancel_job, name='cancel_job'),
    path('reset_password', views.reset_password_page, name='reset_password'),
    path('settings', views.settings_page, name='settings'),
    path('reject', views.reject_access, name='reject'),
    re_path('^flower/.*', views.flower, name='flower'),
    path('', include(router.urls)),
    path('api/submit/', views.api_submit),
    path('api/download/', views.api_download),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

server/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.base import File
from . import env
from .utils import upload_file
from .runner.runner import run_job

from celery import shared_task
#from celery.utils.log import get_task_logger

import json
import logging
import tempfile
from time import sleep
from path import Path


def _get_task_logger(job_id):
    logger = logging.getLogger(str(job_id))
    logger.setLevel(logging.DEBUG)
    job = Job.objects.get(job_id=job_id)
    h = logging.FileHandler(job.get_dir().joinpath('task.log'), mode='a')
    f = logging.Formatter('%(asctime)s [%(levelname)s]: %(message)s')
    h.setFormatter(f)
    logger.addHandler(h)
    return logger


@shared_task(bind=True, acks_late=True, track_started=True, default_retry_delay=30, autoretry_for=(Exception,), max_retries=1)
def submit_job(self, job_id):
    logger = _get_task_logger(job_id)
    try:
        job = Job.objects.get(job_id=job_id)
        cur_status = job.status
        if cur_status in Job.STATUS_FINISHED:
            logger.info(f'Restarting job {job_id} in L.STR (currently in {cur_status})')
            job.status = 'L.STR'
            job.save()
        else:
            logger.info(f'Starting job {job_id} in {cur_status} (it was interrupted half-way)')
        run_job(job)
    except Exception as e:
        logger.exception(e)
        Job.objects.get(job_id=job_id).local_error('Unknown error')
        raise


class Job(models.Model):
    STATUS_CHOICES = (
        ('L.STR', 'Starting the job'),
        ('R.RUN', 'Running'),
        ('L.FIN', 'Finalizing job'),
        ('L.CPL', 'Job completed'),
        ('L.PDB', 'No templates found'),
        ('L.ERR', 'Error'),
        ('R.ERR', 'Error'),
    )

    # All other statuses mean the job is still running
    STATUS_FINISHED = ('L.CPL', 'L.PDB', 'L.ERR', 'R.ERR')

    # SCC queue status
    QUEUE_CHOICES = (
        ('QUE', 'in queue'),
        ('RUN', 'running'),
        ('ERR', 'exited with error'),
        ('FIN', 'finished'),
        ('NAN', '')
    )

    job_id = models.AutoField(primary_key=True)
    job_name = models.CharField(max_length=100, default="", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    warning = models.CharField(max_length=1000, default="", blank=True)
    error = models.CharField(max_length=1000, default="", blank=True)
    deleted = models.BooleanField(default=False)
    restarted = models.IntegerField(default=0)
    touched = models.DateTimeField(auto_now=True)
    queue_id = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ip = models.GenericIPAddressField()
    celery_id = models.CharField(max_length=200, default="", blank=True)

    status = models.CharField(max_length=5, choices=STATUS_CHOICES, default='L.STR')
    queue_status = models.CharField(max_length=3, choices=QUEUE_CHOICES, default='NAN')
    details_json = models.CharField(max_length=1000, blank=True)

    _temp_dir = ''

    def __str__(self):
        attr_list = [self.job_id, self.user, self.status]
        return '-'.join(map(str, attr_list))

    def __getattr__(self, attr):
        json_str = super(Job, self).__getattribute__("details_json")
        if json_str:
            json_dict = json.loads(json_str)
            if attr in json_dict:
                return json_dict[attr]
        return super(Job, self).__getattribute__(attr)

    def get_dir(self):
        return env.JOBS_DIR.joinpath(str(self.job_id))

    def get_remote_dir(self):
        return env.REMOTE_JOBS.joinpath(str(self.job_id))

    def get_output_dir(self):
        return self.get_dir().joinpath('output')

    def get_user_dir(self):
        return self.get_dir().joinpath('user')

    def get_user_json(self):
        return self.get_user_dir().joinpath('user.json')

    def get_models_dir(self):
        return self.get_dir().joinpath('minimized')

    def get_scores_csv(self):
        return self.get_output_dir().joinpath('scores.csv')

    def get_models_zip(self):
        return self.get_output_dir().joinpath('models.zip')

    def get_log_txt(self):
        return self.get_output_dir().joinpath('log.txt')

    def get_receptor_pdb(self):
        return self.get_user_dir().joinpath(self.rec_pdb_file)

    def remote_error(self, error):
        self.status = 'R.ERR'
        self.error = error
        self.save()

    def local_error(self, error):
        self.status = 'L.ERR'
        self.error = error
        self.save()

    def reset(self):
        """
        Call this when a job is (re)started. Resets error and warning and increments 'restarted' field
        """
        self.restarted += 1
        self.error = ''
        self.warning = ''
        self.save()

    def start(self):
        if self.celery_id != '':
            result = submit_job.AsyncResult(self.celery_id)
            if not result.ready():
                return [f'Job {self.job_id} is already running (state: {result.state})']
        result = submit_job.apply_async((self.job_id,))
        self.celery_id = result.task_id
        self.restarted += 1
        self.error = ''
        self.warning = ''
        self.save()
        return []

    def cancel(self):
        if self.celery_id != '':
            result = submit_job.AsyncResult(self.celery_id)
            if result.ready():
                return [f'Job has already finished (state: {result.state})']

            result.revoke(terminate=True)
            return [f'Job cancelled (state: {result.state})']
        else:
            return ['Task id is empty']

    def _make_temp_dir(self):
        self._temp_dir = Path(tempfile.mkdtemp(dir=env.TMP_DIR))
        self._temp_dir.chmod(0o755)

    def _create_job_dir(self):
        job_dir = self.get_dir()
        if job_dir.isdir():
            job_dir.rmtree(job_dir)
        self._temp_dir.move(job_dir)

    @staticmethod
    def _get_name_for_uploaded_file(field_name, file):
        src_name = file.name
        src_ext = Path(src_name).ext  # Python's standard `pathlib` uses .suffix, but `path` uses .ext
        out_name = Path(field_name).with_suffix(src_ext)
        return out_name

    def check_user_input(self, form, files):
        error_list = []
        self._make_temp_dir()

        user_dir = self._temp_dir / 'user'
        user_dir.mkdir_p()

        # dump user files in user/
        for name, file in files.items():
            fpath = user_dir / self._get_name_for_uploaded_file(name, file)
            upload_file(file, fpath)

        # dump user data in user/user.json
        with open(user_dir.joinpath('user.json'), 'w') as f:
            data = {k: (
                v if not isinstance(v, File)
                else self._get_name_for_uploaded_file(k, v)) for k, v in form.cleaned_data.items()}
            json.dump(data, f, indent=4)

        return error_list

    def make_dir_and_start(self):
        self._create_job_dir()

        clean_json = self.get_user_json()
        with open(clean_json, 'r') as f:
            details_json = json.load(f)
        self.details_json = json.dumps(details_json)
        self.save()

        self.start()


class ModellerKey(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    key = models.CharField(max_length=300, blank=True, null=True)

server/core/forms.py
from django import forms
from django.contrib.auth.password_validation import password_validators_help_text_html
from django.core.validators import ValidationError
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import User
import warnings

import re
import io
from Bio import SeqIO, PDB
from Bio.PDB.PDBExceptions import PDBConstructionWarning


def validate_sequence(input):
    aa1 = 'A R N D C Q E G H I L K M F P S T W Y V X'
    aa1_split = aa1.split()

    for x in input:
        if x not in aa1_split:
            raise ValidationError('Protein sequence must belong to 21 letter alphabet (found "%s"):\n%s' % (x, aa1))


def validate_fasta(input):
    fasta = io.StringIO(input)
    try:
        fasta_dict = SeqIO.to_dict(SeqIO.parse(fasta, 'fasta'))
    except Exception as e:
        raise ValidationError('Wrong format of FASTA input')
    fasta.close()

    if len(fasta_dict) > 1:
        raise ValidationError('More, than one sequence provided')

    if len(fasta_dict) < 1:
        raise ValidationError('No sequences provided')

    return fasta_dict


def validate_file(f):
    allowed_size_mb = 8
    if f.size > 1024 * 1024 * allowed_size_mb:
        raise ValidationError(f'Uploaded file cannot be larger than {allowed_size_mb} MB')


def validate_pdb(pdb_file):
    if not pdb_file.name.endswith('.pdb'):
        raise ValidationError('Must be a file with .pdb extension')

    warnings.simplefilter('ignore', PDBConstructionWarning)  # Silence annoying warnings cluttering web server's log
    parser = PDB.PDBParser()

    # if no decoding is done, parser just skips it all
    with io.StringIO(pdb_file.read().decode("utf-8")) as buf:
        pdb_file.seek(0)

        try:
            pdb = parser.get_structure('pdb', buf)
        except Exception as e:
            raise ValidationError("Couldn't parse PDB file: " + str(e))

        if len(list(pdb.get_models())) > 1:
            raise ValidationError("Only PDB files containing one model are supported")

        if len(list(pdb.get_atoms())) == 0:
            raise ValidationError("Didn't find any atoms in PDB file")

        for chain in pdb.get_chains():
            chain_id = chain.get_id()[-1]
            if len(chain_id) != 1:
                raise ValidationError("Invalid chain is present: " + str(chain_id))
            if chain_id == ' ':
                raise ValidationError("PDB can not contain atoms with empty chain field")



class JobSubmitForm(forms.Form):
    job_name = forms.CharField(label='Job name',
                               help_text='Enter your job name here',
                               max_length=100,
                               required=False)

    rec_pdb_file = forms.FileField(label='Protein *',
                                   help_text='Provide your docking target',
                                   required=True,
                                   validators=[validate_file, validate_pdb])

    rec_chain = forms.CharField(label='Chain ID *',
                                help_text='Enter name of the protein chain',
                                max_length=1,
                                required=True)

    lig_smiles = forms.CharField(label='Ligand SMILES *',
                                 help_text='Enter your ligand in SMILES format',
                                 required=True)

    pdb_exc = forms.CharField(label='PDB exclusions',
                              help_text='Enter a list of PDB codes, which will be excluded from homology search (comma separated)',
                              required=False)

    modeller_key = forms.CharField(label='MODELLER key',
                                   help_text='Enter your MODELLER key or obtain one from <a href=https://salilab.org/modeller/registration.html>here</a>',
                                   required=False)

    no_remodeling = forms.BooleanField(label='Do not remodel',
                                       help_text="Check if you don't want your protein to be remodeled based on chosen template",
                                       required=False)

    def clean_lig_smiles(self):  # TODO: add smiles validation
        smi = self.cleaned_data.get('lig_smiles')
        if len(smi.split()) != 1:
            self.add_error('lig_smiles', 'Only single ligand can be supplied at a time. Spaces and line-breaks are not allowed.')
        return smi

    def clean_pdb_exc(self):
        pdb_list = self.cleaned_data.get('pdb_exc')
        if not pdb_list:
            return []

        try:
            pdb_list = pdb_list.split(',')
            pdb_list = list(map(lambda x: x.strip().upper(), pdb_list))
        except Exception as e:
            self.add_error('pdb_exc', 'Wrong format of PDB exclusions')
            return []

        for pdb in pdb_list:
            if len(pdb) != 4:
                self.add_error('pdb_exc', 'Wrong PDB code: ' + pdb)
                return []

        return pdb_list

    def clean_rec_chain(self):
        if len(self.cleaned_data.get('rec_chain')) != 1:
            self.add_error('rec_chain', 'Chain name must be a single letter')

        return self.cleaned_data.get('rec_chain')

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('no_remodeling') and cleaned_data.get('modeller_key') == '':
            self.add_error('modeller_key', 'MODELLER key is required unless "Do not remodel" is checked')

        return cleaned_data


class SettingsForm(forms.Form):
    current_password = forms.CharField(label='Current password',
                                       max_length=100,
                                       required=True,
                                       help_text='Please enter your current password',
                                       widget=forms.PasswordInput(attrs={'class': 'form-control _password'}))

    password = forms.CharField(label='Password',
                               max_length=100,
                               required=True,
                               validators=[validate_password],
                               help_text=password_validators_help_text_html(),
                               widget=forms.PasswordInput(attrs={'class': 'form-control _password'}))


class AcademicEmailField(forms.EmailField):
    def validate(self, value):
        super().validate(value)
        # List based on Wikipedia (https://en.wikipedia.org/wiki/.edu_(second-level_domain) and https://en.wikipedia.org/wiki/.edu_(second-level_domain))
        tld_good = (r'\.edu$', r'\.edu\.[a-z]+$', r'\.ac\.[a-z]+$')
        if not any(re.match(r'^.*@.*'+tld, value) for tld in tld_good):
            raise ValidationError('Your e-mail must belong to an academic domain (.edu, .edu.*, .ac.*)')
        if User.objects.filter(email__exact=value).exists():
            raise ValidationError('Provided email is already in the database')


class SignUpForm(forms.Form):
    email = AcademicEmailField(label='E-mail *',
                               required=True,
                               max_length=1000,
                               help_text='Please, provide a valid academic e-mail address (.edu, .edu.*, .ac.*), we will use it to send you your password',
                               widget=forms.EmailInput(attrs={'class': 'form-control',
                                                              'style': 'width: 40ch'}))

    first_name = forms.CharField(label='First Name',
                                 max_length=1000,
                                 required=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'style': 'width: 40ch'}))

    last_name = forms.CharField(label='Last Name',
                                max_length=1000,
                                required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'style': 'width: 40ch'}))


def username_not_exists_validator(value):
    if not User.objects.filter(username__exact=value).exists():
        raise ValidationError('Sorry, we couldn\'t find the e-mail you provided')


class PasswordResetForm(forms.Form):
    username = forms.CharField(label='E-mail',
                               required=True,
                               max_length=1000,
                               help_text='Please, enter your e-mail address',
                               validators=[username_not_exists_validator],
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'style': 'width: 40ch'}))

server/core/templates/core/contact.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

    <div class="my-fixed-width text-center">
        <h2>Contact</h2>
        Please direct all correspondence to <a href="mailto:ligtbm@gmail.com">ligtbm@gmail.com</a>
    </div>
    <br/>

{% endblock %}

server/core/templates/core/generic_form.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <h3 align="center">{{ page_title }}</h3>
    <p align="center">{{ page_description }}</p>
    <form class="my-generic-form" action={% url request.resolver_match.url_name %} method="post">
        {% csrf_token %}
        <div class="_generic_form">
            {% for field in form %}

                <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    {% endif %}
                </div>

                {% if field.help_text %}
                    <p class="_help-text" align="center">{{ field.help_text }}</p>
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-md" style="margin-top: 25px" value="submit">{{ submit_text }}</button>
        </div>
    </form>
{% endblock %}

server/core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}

{% block header_add %}
    <link rel='stylesheet' type='text/css' href={% static "core/css/home.css" %} xmlns="http://www.w3.org/1999/html"/>
    <link rel='stylesheet' type='text/css' href={% static "core/css/spinner.css" %} />
    <link rel='stylesheet' type='text/css' href={% static "core/css/apple-checkbox.css" %} />
    <link rel='stylesheet' type='text/css' href={% static "core/css/drop-file.css" %} />
{% endblock %}

{% block content %}
    <form class="form-jobs" enctype='multipart/form-data' action={% url "index" %} method='post'>
    {% csrf_token %}
        <h1 align="center">Docking</h1>
        <br>

        {# Job name #}
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <div class="form-group {% if form.job_name.errors %}has-error has-feedback{% endif %}"
                     style="text-align: center;">
                    <label for="id_job_name" style="font-weight: normal;">{{ form.job_name.label }}</label>
                    <input class="form-control center-text"
                           style="height: 40px; margin:auto;"
                           type="text" name="job_name" id="id_job_name" placeholder="1AVX_lig" maxlength="100"/>
                    {% if form.job_name.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    {% endif %}
                    <p class="_help-text" align="center">{{ form.job_name.help_text }}</p>
                </div>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="col-sm-4 col-sm-offset-2">
                <div style="display: flex; justify-content: center; align-items: center">
                    <div class="form-group {% if form.rec_pdb_file.errors %}has-error has-feedback{% endif %}"
                         style="text-align: center;">
                        <label for="id_rec_pdb_file" style="font-weight: normal;">{{ form.rec_pdb_file.label }}</label>
                        <div class="wrapper">
                            <div class="file-upload" {% if form.rec_pdb_file.errors %}style="border-color: #a42727; color: darkred;"{% endif %}>
                                <input type="file" name="rec_pdb_file" id="id_rec_pdb_file" required>
                                <span class="glyphicon glyphicon-cloud-upload" style="font-size: 15px"></span>
                                <p style="margin-top:auto; margin-bottom:auto;">&nbsp&nbspUpload PDB file</p>
                                {% if form.rec_pdb_file.errors %}
                                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                                {% endif %}
                            </div>
                        </div>
                        <p class="_help-text" align="center">{{ form.rec_pdb_file.help_text }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div style="display: flex; justify-content: center; align-items: center">
                    <div class="form-group {% if form.rec_chain.errors %}has-error has-feedback{% endif %}"
                         style="text-align: center;">
                            <label for="id_rec_chain" style="font-weight: normal;">{{ form.rec_chain.label }}</label>
                            <input type="text"
                                   class="form-control center-text"
                                   style="margin:auto; height:40px;"
                                   name="rec_chain" id="id_rec_chain" placeholder="A" maxlength="1" required>
                            {% if form.rec_chain.errors %}
                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                            {% endif %}
                        <p class="_help-text" align="center">{{ form.rec_chain.help_text }}</p>
                    </div>
                </div>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="form-group {% if form.lig_smiles.errors %}has-error has-feedback{% endif %}"
                     style="text-align: center;">
                    <label for="id_lig_smiles" style="font-weight: normal;">{{ form.lig_smiles.label }}</label>
                    <textarea class="form-control"
                              rows="1"
                              style="margin:auto"
                              name="lig_smiles" id="id_lig_smiles"
                              placeholder="C1C2C(C(S1)CCCCC(=O)O)NC(=O)N2" required></textarea>
                    {% if form.lig_smiles.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    {% endif %}
                    <p class="_help-text" align="center">{{ form.lig_smiles.help_text }}</p>
                </div>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="form-group {% if form.pdb_exc.errors %}has-error has-feedback{% endif %}"
                     style="margin:auto; text-align: center;">

                    <label for="id_pdb_exc" style="font-weight: normal;">{{ form.pdb_exc.label }}</label>
                    <textarea class="form-control"
                              style="font-size: 14px;"
                              rows="6"
                              name="pdb_exc" id="id_pdb_exc" placeholder="1AO7,4CS4,4Q4W,.."></textarea>
                    {% if form.pdb_exc.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    {% endif %}
                    <p class="_help-text" align="center">
                        {{ form.pdb_exc.help_text }}
                    </p>
                </div>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-sm-5">
                <div style="display: flex; height: 100px; justify-content: center; align-items: center">
                    <div>
                        <div class="form-group {% if form.modeller_key.errors %}has-error has-feedback{% endif %}" style="text-align: center;">
                            <label style="font-weight: normal" for="id_modeller_key">{{ form.modeller_key.label }}</label>
                            <textarea rows="1" class="form-control" style="font-size: 14px;"
                                      name="modeller_key" id="id_modeller_key">{{ modeller_key }}</textarea>
                            {% if form.modeller_key.errors %}
                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                            {% endif %}
                        </div>
                        {% autoescape off %}
                            <p class="_help-text" align="center">{{ form.modeller_key.help_text }} </p>
                        {% endautoescape %}
                    </div>
                 </div>
            </div>

            <div class="col-sm-2">
                <div style="display: flex; height: 100px; justify-content: center; align-items: center">
                    <b style="border: 1px solid dimgrey; border-radius: 50px; padding: 10px; line-height: normal">OR</b>
                </div>
            </div>

            <div class="col-sm-5">
                <div style="display: flex; height: 100px; justify-content: flex-start; align-items: center; padding-top:10px">
                    <div>
                        <div class="form-group {% if form.no_remodeling.errors %}has-error has-feedback{% endif %}"
                             style="margin:auto; width:fit-content; width: -moz-fit-content">
                            <input type="checkbox" id="id_no_remodeling" name="no_remodeling" class="ios8-switch ios8-switch-lg">
                            {% if form.no_remodeling.errors %}
                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                            {% endif %}
                            <label for='id_no_remodeling' style="font-weight: normal; line-height: 20px;">{{ form.no_remodeling.label }}</label>
                        </div>
                        <p class="_help-text" align="center">{{ form.no_remodeling.help_text }}</p>
                    </div>
               </div>
            </div>
        </div>

        <hr>

        {% if user.username == "anonym" %}
            <div style="display: flex; justify-content: center">
                <div class="form-group" style="margin: 0 auto; width: fit-content; width: -moz-fit-content">
                    <input type="checkbox" id="id_noncommercial" class="ios8-switch ios8-switch-lg" required>
                    <label for='id_noncommercial' style="font-weight: normal; line-height: 20px;">I will use LigTBM for non-commercial purposes only</label>
                </div>
            </div>
        {% endif %}

        {# Submit button #}
        <div class="form-group jobs-submit text-center">
            <button type="submit" class="btn btn-primary btn-md" id="submit_button" name="action" value="submit">Submit job</button>
        </div>

        <div id="spinner" style="display: none">
            <p align="center">Processing input..</p>
            <div class="spinner" style="margin: auto;"></div>
        </div>
    </form>

{% endblock %}

server/core/templates/core/login.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron" style="background-color: rgba(126,166,237,0.8)">
	<h1 style="color: black">Welcome to {{ SERVER_NAME }}</h1>
	<p style="color:black; font-weight: normal">Automated server for template-based small-molecule docking</p>
    <a class="btn btn-md btn-link" style="white-space: normal; color: black;" href="{% url 'login' %}?anonym=true">
        Use the server without the benefits of your own account &raquo;
    </a>
</div>

<form class="form-horizontal my-signin-form" enctype="multipart/form-data" action={% url "login" %} method="post">
    {% csrf_token %}

	<h2 class="white-outline">Please sign in</h2>

    <div class="form-group">
        <input type="text" id="username" class="form-control" name="username"
               value="" placeholder="E-mail" required autofocus>
    </div>

    <div class="form-group">
        <input type="password" id="password" class="form-control" name="password"
               value="" placeholder="Password" required>
    </div>

    <div class="form-group">
        <a class="btn btn-sm btn-link white-outline" style="color: black;" href='{% url "reset_password" %}'>Forgot password?</a>
    </div>

     <div class="text-center">
	    <button class="btn btn-md btn-success btn-block" type="submit" name="action" value="Login">Sign in</button>
     </div>
</form>

{% endblock %}

server/core/templates/core/publications.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <div class="my-fixed-width text-center">
        <h2>Papers</h2>
        <p class="text-left"> When using the results of this server in a scientific publication, please cite the following papers:</p>
        <ol class="text-left">
                <li>Kotelnikov, Alekseenko, Liu, Ignatov, Padhorny, Brini, Lukin, Coutsias, Dill, Kozakov
                    <i>"Sampling and refinement protocols for template-based macrocycle docking: 2018 D3R Grand Challenge 4,&rdquo;</i>
                    Journal of Computer-Aided Molecular Design <b>34</b>, 179&ndash;189 (2020)
                    <a href="https://doi.org/10.1007/s10822-019-00257-1">doi:10.1007/s10822-019-00257-1</a>
                    (<a href={% static "core/files/LigTBM-Kotelnikov2020.pdf" %}>accepted pdf</a>)
              </li>
              <li>Alekseenko, Kotelnikov, Ignatov, Egbert, Kholodov, Vajda, Kozakov
                  <i>"ClusPro LigTBM: Automated Template-Based Small Molecule Docking,&rdquo;</i>
                  Journal of Molecular Biology (2019)
                  <a href="https://doi.org/10.1016/j.jmb.2019.12.011">doi:10.1016/j.jmb.2019.12.011</a>
                  (<a href={% static "core/files/LigTBM-Alekseenko2020.pdf" %}>accepted pdf</a>)
              </li>
        </ol>
    </div>
{% endblock %}